id: IF5FC1D5B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:22:55+00:00'
last_modified: '2022-06-08T01:21:05.616677+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W14592
  title: གསུང་འབུམ། བློ་བཟང་ཡེ་ཤེས་བསྟན་འཛིན་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E3BF:
      image_group_id: I1629
      title: ''
      total_pages: 674
      order: 1
      base_file: E3BF.txt
    '9259':
      image_group_id: I1630
      title: ''
      total_pages: 631
      order: 2
      base_file: 9259.txt
    D163:
      image_group_id: I1631
      title: ''
      total_pages: 661
      order: 3
      base_file: D163.txt
    4B16:
      image_group_id: I1632
      title: ''
      total_pages: 559
      order: 4
      base_file: 4B16.txt
    80E4:
      image_group_id: I1633
      title: ''
      total_pages: 557
      order: 5
      base_file: 80E4.txt
    5AAA:
      image_group_id: I1634
      title: ''
      total_pages: 816
      order: 6
      base_file: 5AAA.txt
    8DAD:
      image_group_id: I1635
      title: ''
      total_pages: 794
      order: 7
      base_file: 8DAD.txt
    2E4D:
      image_group_id: I1636
      title: ''
      total_pages: 347
      order: 8
      base_file: 2E4D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
